### ISSUE TITLE
unable to install package

### ISSUE THREAD

**Issue by KDIncognito** [trinker/tagger#9]
Hi,

I Had to reinstall OS on my system, so I have to now install all the R libraries. I tried the zip, tar, and the pacman command versions to install these packages. I also tried "`install_github(trinker/tagger)`"-devtools library. I could only install `coreNLPsetup`, and not the other two. I tried this approach on other machines, and got same results. Please help! Thank you!

Final error message I receive is here (64 bit machine, OS- Windows 7, RAM 8GB, also tried on an Optiplex 64 bit, 32GB RAM). I tried installing only tagger when I got this error. Error message will include termco if I included it too. No change :(

```
ERROR: dependency 'termco' is not available for package 'tagger'
* removing 'C:/Users/KD/Documents/R/win-library/3.4/tagger'
Warning message:
In pacman::p_load_gh(c("trinker/tagger")) : 
Failed to install/load:
trinker/tagger
```
Termco and tagger
```
Warning message:
In pacman::p_load_gh(c("trinker/termco", "trinker/tagger")) : 
Failed to install/load:
trinker/termco, trinker/tagger
```

**Comment by trinker** [comment]
If you read the README file I think you'll be able to figure out the way to install: https://github.com/trinker/tagger/blob/master/README.md

Can you take a look and let me know.  If installation isn't clear I'll update the readme to make it clearer.

**Comment by KDIncognito** [comment]
Thank you for your response! That command using pacman library was the first thing I tried. It did not work. That is when I found that I could install coreNLPsetup, but not the other two, so I tried those other variations I mentioned above. Am I doing it wrong?

**Comment by trinker** [comment]
Try:

```
if (!require("pacman")) install.packages("pacman")
pacman::p_load_gh(c(
    "trinker/termco", 
    "trinker/coreNLPsetup",        
    "trinker/tagger"
))
```

**Comment by KDIncognito** [comment]
I could install it earlier, on my old OS, I had trouble installing it later on. I think I could installed the libraries manually around the same time I raised this issue. It is ok now. I think the problem was with my OS and not your instructions. They are perfect!, and thank you for your response. Cheers!

**Comment by zunman** [comment]
I have the same error. How did you resolve it? @sreekrishnadutta
